### ISSUE TITLE
SQL Task

### ISSUE THREAD

**Issue by elubik** [acivitillo/python_data_products_workshop#23]

**Comment by elubik** [comment]
1. additionally "import os" was required (but this was already presented ;) )

**Comment by elubik** [comment]
2. misspelling in "root_path" vs "path_root" (you also mentioned about that)

**Comment by acivitillo** [comment]
@elubik yeah I know, good to learn some stack traces ;)

**Comment by elubik** [comment]
Code Snippet - SQL Only

Done

**Comment by elubik** [comment]
Code Snippet 2 - SQL + Pandas

Done.

(Completed on different machine - definitely something with pandas version on old laptop)
