### ISSUE TITLE
Import Airly sensors measurements into database

### ISSUE THREAD

**Issue by rafalroman** [acivitillo/python_data_products_workshop#33]
Import Airly sensors measurements into database

**Comment by acivitillo** [comment]
@rafalroman please check my answer here https://stackoverflow.com/questions/60871938/how-do-i-get-a-dask-dataframe-into-a-mysql-datatable/60899329#60899329

You should try to used the `COPY` statement from postgres and not the `to_sql()` pandas. Pandas sends data to the db via odbc which is very slow and ineffienct. `COPY` is a built in ingestion command for postgres (and redshift).
